import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const models = readFileSync(new URL('../modular-models.js', import.meta.url), 'utf8');
const voice = readFileSync(new URL('../openai-voice.js', import.meta.url), 'utf8');
const interpreter = readFileSync(new URL('../realtime-turn-interpreter.js', import.meta.url), 'utf8');
const controller = readFileSync(new URL('../voice-pipeline-controller.js', import.meta.url), 'utf8');
const server = readFileSync(new URL('../server-modular.js', import.meta.url), 'utf8');

function speechStartedBlock(source) {
  const start = source.indexOf('onSpeechStarted: () =>');
  const end = source.indexOf('onTranscript:', start);
  assert.notEqual(start, -1, 'onSpeechStarted block must exist');
  assert.notEqual(end, -1, 'onSpeechStarted block must end before onTranscript');
  return source.slice(start, end);
}

test('only gpt-realtime-mini is configured as an AI model', () => {
  assert.match(models, /gpt-realtime-mini/);
  assert.doesNotMatch(models, /gpt-4o-mini-transcribe/);
  assert.doesNotMatch(models, /gpt-4o-mini-tts/);
  assert.doesNotMatch(voice, /gpt-4o-mini-transcribe/);
  assert.doesNotMatch(voice, /gpt-4o-mini-tts/);
  assert.doesNotMatch(voice, /\/v1\/audio\/speech/);
  assert.doesNotMatch(voice, /MODELS\.transcription/);
  assert.doesNotMatch(voice, /MODELS\.speech/);
});

test('Realtime Mini listens natively without a transcription model', () => {
  assert.match(voice, /transcription: null/);
  assert.match(voice, /input_audio_buffer\.committed/);
  assert.match(voice, /Transcribe only the most recent caller audio turn/);
  assert.match(voice, /conversation: 'auto'/);
});

test('turn detection waits for a real silence and never auto-interrupts', () => {
  assert.match(voice, /type: 'server_vad'/);
  assert.match(voice, /silence_duration_ms: Math\.max\(1200/);
  assert.match(voice, /create_response: false/);
  assert.match(voice, /interrupt_response: false/);
  assert.doesNotMatch(voice, /eagerness: 'high'/);
  assert.match(controller, /callerSpeaking/);
  assert.match(controller, /state\.callerSpeaking \|\| state\.interpreting/);
});

test('caller-facing speech is generated by the same Realtime session', () => {
  assert.match(voice, /output_modalities: \['audio'\]/);
  assert.match(voice, /response\.output_audio\.delta/);
  assert.match(voice, /format: \{ type: 'audio\/pcmu' \}/);
  assert.match(voice, /speech_request_id/);
  assert.match(voice, /REALTIME_SPEECH_MISMATCH/);
  assert.match(controller, /engine: 'realtime'/);
  assert.doesNotMatch(controller, /engine: 'speech-api'/);
});

test('interpretation and speech requests have bounded retries and timeouts', () => {
  assert.match(voice, /TEXT_TIMEOUT_MS/);
  assert.match(voice, /SPEECH_TIMEOUT_MS/);
  assert.match(voice, /TEXT_ATTEMPTS/);
  assert.match(voice, /SPEECH_ATTEMPTS/);
  assert.match(voice, /Realtime speech timed out/);
});

test('Realtime interpreter returns bounded JSON instead of caller-facing prose', () => {
  assert.match(interpreter, /return exactly one compact JSON object/i);
  assert.match(interpreter, /Do not write a caller-facing response/i);
  assert.match(interpreter, /Never suggest hiring or contacting a painter/i);
  assert.match(interpreter, /Never copy unchanged values from currentLead/i);
  assert.match(interpreter, /INTERPRETER_ACTIONS/);
  assert.match(interpreter, /INTERPRETER_ACKS/);
});

test('controller consumes realtime interpretation but owns question order', () => {
  assert.match(controller, /realtimeVoice\.interpret/);
  assert.match(controller, /parseRealtimeTurnInterpretation/);
  assert.match(controller, /applyRealtimeInterpretation/);
  assert.match(controller, /nextRequiredQuestion/);
  assert.match(controller, /baseQuestionFor/);
  assert.match(controller, /fastInterpretation/);
  assert.match(controller, /interpretationHasCurrentField/);
  assert.doesNotMatch(controller, /decideReceptionistTurn/);
});

test('more-questions no always routes to the closing line', () => {
  assert.match(controller, /não\|nao/);
  assert.match(controller, /MORE_QUESTIONS_NO/);
  assert.match(controller, /return speakClosingAndEnd\(\)/);
  assert.match(controller, /i said no/);
});

test('caller speech start no longer invalidates the same transcript interpretation', () => {
  assert.doesNotMatch(speechStartedBlock(controller), /turnRevision\s*\+=/);
  assert.match(speechStartedBlock(controller), /state\.callerSpeaking = true/);
});

test('controller advances the pending question before speech generation finishes', () => {
  assert.match(controller, /state\.memory\.currentQuestionId = questionId/);
  assert.match(controller, /effectiveQuestionId = nextQuestionId !== 'none'/);
});

test('summary corrections are applied once and field-targeted', () => {
  assert.match(controller, /interpretation\.action === 'summary_correction' && changes\.length/);
  assert.match(controller, /my full name is\|my name/);
  assert.doesNotMatch(controller, /not\\s\+\[A-Za-z\].*it's\|it is/);
});

test('lead submission grants time to ask more questions and close normally', () => {
  assert.match(server, /POST_SUBMISSION_GRACE_MS = 90 \* 1000/);
  assert.match(server, /grantPostSubmissionGrace\(ctx\)/);
  assert.match(server, /call\.post_submission_grace_started/);
  assert.match(server, /snapshot\?\.interpreting/);
});
